type Mutation {
  # Test
  createTest(testInput: TestInput!): String! @deprecated

  # User
  createUser(input: CreateUserInput!): UserResponse!
  updateUser(input: UpdateUserInput!): UserResponse!

  # League
  createLeague(input: CreateLeagueInput!): LeagueResponse!

  # Season
  # createSeason(input: CreateSeasonInput!): SeasonResponse!
  "Creates a season with the selected teams along with the selected captains"
  createFullSeason(input: CreateFullSeasonInput!): ID!
  updateSeason(input: UpdateSeasonInput!): SeasonResponse!
  deleteSeason(input: DeleteSeasonInput!): Boolean!
  addTeamToSeason(input: AddTeamToSeasonInput!): ID!

  # Storyline
  createStoryline(input: CreateStorylineInput!): StorylineResponse!
  "Updates the storyline"
  updateStoryline(input: UpdateStorylineInput!): StorylineResponse!
  deleteStoryline(input: DeleteStorylineInput!): Boolean!

  # Award
  createAward(input: CreateAwardInput!): AwardResponse!

  # Team
  createTeam(input: CreateTeamInput!): CreateTeamResponse!
  updateTeam(input: UpdateTeamInput!): UpdateTeamResponse!
  "Drafts a player to a team. Typically occurs before the Season starts"
  draftPlayerToTeam(input: DraftPlayerInput!): ID!
  "Removes a player from a team during a season"
  removePlayerFromTeam(input: DraftPlayerInput!): Boolean!


  # Event
  createEvent(input: CreateEventInput!): EventResponse!
  updateEvent(input: UpdateEventInput!): EventResponse!
}

input TestInput {
  name: String!
  age: Int!
}
