import './globals.css';
import type {Metadata} from 'next';
import {Inter} from 'next/font/google';
import {Providers} from './providers';
import type {ReactNode} from 'react';
import {NavBar} from '../components/fhl/Nav';

// eslint-disable-next-line new-cap
const inter = Inter({subsets: ['latin']});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <NavBar>
            {children}
          </NavBar>
        </Providers>
      </body>
    </html>
  );
}

